### ISSUE TITLE
Bug for Jellyfin 10.6.0

### ISSUE THREAD

**Issue by Protektor-Desura** [nielsvanvelzen/jellyfin-plugin-vgmdb#1]
I am getting this error in Jellyfin 10.6.0

[18:31:10] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error loading types from Jellyfin.Plugin.Vgmdb, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
System.TypeLoadException: Method 'get_ProviderName' in type 'Jellyfin.Plugin.Vgmdb.ExternalIds.VgmdbAlbumExternalId' from assembly 'Jellyfin.Plugin.Vgmdb, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()

I noticed the GitHub said you did an update for 10.6.0. When do you think you will put up a new release with the fixes and are you planning to create a repository for it hosted here on GutHub? It isn't hard. I set one up here on GitHub and it only took about 10-20 minutes to set it up and zip everything up for a plugin.

**Comment by nielsvanvelzen** [comment]
I updated the plugin just before I left on vacation. When I'm back I'd like to setup a repository for easy use of my plugins.

If you want to use the plugin right now you need to build it from source.

**Comment by nielsvanvelzen** [comment]
@Protektor-Desura I just released version 1.1.0.0 which works with Jellyfin 10.6. I will look into creating a repository later!
